config/routes.rb
Rails.application.routes.draw do
  

  root 'articles#index'

  resources :tags

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_and_belongs_to_many :tags
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @tags = Tag.limit(5)
    if !params.key?("q")
      @articles = Article.all.order(created_at: :desc)
    else 
      @articles = Article.where("lower(title) LIKE '%#{params[:q].downcase}%'" ).order(created_at: :desc)
    end
    @params = params
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    article = Article.find(params[:id])
    article.views_count = article.views_count == nil ? 1 : article.views_count+1
    article.save
    @article = article

    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/new
  def new
    @article = Article.new
    @tags = @article.tags.map { |tag| tag.name }
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    @tags = @article.tags.map { |tag| tag.name }
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    
    @tags = params[:tags_field].split(/\s*,\s*/)
    tags = @tags.map{ |tag| Tag.find_or_create_by(name: tag) } 
    @article.tags.clear
    @article.tags << tags

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @tags = params[:tags_field].split(/\s*,\s*/)
    tags = @tags.map{ |tag| Tag.find_or_create_by(name: tag) } 
    @article.tags.clear
    @article.tags << tags

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end

    def tags_params
      params.permit(:tag_fields)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment_params = comment_params
    redirect_to article_path(@article)
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :content)
      # params.fetch(:comment, {})
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]

  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<div class="card mb-4">
  <div class="card-block">
    <h4 class="card-title"><%= link_to(article.title, article_path(article)) %></h4>
    <p class="card-text"><%= @markdown.render(article.body).html_safe %></p>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-warning' %>
    <%= link_to 'Delete', article, class: 'btn btn-danger mr-3', method: :delete, data: { confirm: 'Are you sure you want to delete?'} %>
    <%= article.views_count ? article.views_count : '0' %> view(s)
  </div>
</div>

app/views/articles/_comment_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for [@article, @article.comments.build] do |f| %>
      <div class="form-group">
        <%= f.label :author %><br>
        <%= f.text_field :author, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %><br>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tags_field %><br>
    <%= text_field_tag :tags_field, @tags.join(', '), class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 8, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<%= debug(@tags) %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Editing Article</h1>
  <%= render 'form' %>

  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
  
</div>

app/views/articles/index.html.erb
<div class="container">
  <% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <h1>
    My blogs <%= link_to 'New Article', new_article_path, class: 'btn btn-secondary' %>
    
  </h1>
  <h3>My first rails application for CoderSchool</h3>
  <div>
    <form action="" class="form-inline mb-3">
      <input class="form-control mr-3" type="text" name='q' class="search" value="<%= @params.key?(:q) ? @params[:q] : '' %>">
      <button class="btn btn-default mr-3" type="submit">Search</button>
      <%= @params.key?(:q) ? (link_to 'Clear Search', articles_path) : '' %>
    </form>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <%= render @articles %>
    </div>
    <div class="col-sm-4">
      <div class="widget">
        <h3>Tags:</h3>
        <ul>
          <% @tags.each do |tag| %>
            <li><%= link_to tag.name, tag %></li>   
          <% end %>
         </ul>
      </div>
    </div>
  </div>
  
  <br>
  
  
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>New Article</h1>
  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
  <% end %>

  <h1 class="article-title"><%= @article.title %></h1>

  <div class="meta">
    <span class="tags"><strong>Tags:</strong> 
      <% if @article.tags.empty? %>
        this article has no tag
      <% else %>
        <%= @article.tags.map { |tag| link_to tag.name, tag }.join(', ').html_safe %>
      <% end %>
    </span>
  </div>
  
  <div class="block-content mt-4">
    <%= @markdown.render(@article.body).html_safe%>
    <p class="small"><%= @article.views_count%> View(s)</p>
  </div>

  <div class="comments mb-4">
    <h3>Comments</h3>
    <% @article.comments.each do |comment| %>
      <div class="card comment mb-3">
        <div class="card-block">
          <h6 class="author"><%= comment.author %> said:</h6>
          <div class="content"><%= @markdown.render(comment.content).html_safe %> </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="comment-form">
    <h3>New comment</h3>
    <%= render 'comment_form' %>
  </div>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>

</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= @comment_params %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-light navbar-toggleable-md bd-navbar">
    <div class="container">
      <div class="d-flex justify-content-between hidden-lg-up">
        <a class="navbar-brand" href="/">
          Blog
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#bd-main-nav" aria-controls="bd-main-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="bd-main-nav" aria-expanded="false">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <%= link_to 'Homepage', '/', class: "nav-item nav-link"%>
          </li>
          <li class="nav-item <%= params[:controller] == 'articles' ? 'active' : '' %>">
            <%= link_to 'Posts', articles_path, class: "nav-item nav-link"%>
          </li>
        </ul>
      </div>
    </div>
  </header>

<%= yield %>

</body>
</html>

app/views/tags/show.html.erb
<div class="container">
  <h1>Tags: <%= @tag.name %></h1>
  <div class="row">
    <div class="col-md-8">
      <div class="article-list">
        <% @tag.articles.each do |article| %>
          <div class="card mb-4">
            <div class="card-block">
              <h4 class="card-title"><%= link_to(article.title, article_path(article)) %></h4>
              <p class="card-text"><%= @markdown.render(article.body).html_safe %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-warning' %>
              <%= link_to 'Delete', article, class: 'btn btn-danger mr-3', method: :delete, data: { confirm: 'Are you sure you want to delete?'} %>
              <%= article.views_count ? article.views_count : '0' %> view(s)
            </div>
          </div>
        <% end %>
      </div>  
    </div>
  </div>

</div>